# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

xcodeproj 'XMGTV.xcodeproj'

target 'XMGTV' do

pod 'Alamofire'
pod 'Kingfisher'
pod 'ProtocolBuffers-Swift'

end
